[package]
name = "meowith"
version = "0.1.0"
edition = "2021"

[workspace]

members = [
    "node",
    "data",
    "controller",
    "commons",
    "logging",
    "protocol",
    "tests"
]

[dependencies]
scylla = "0.13.1"
