[package]
name = "network"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl = "0.10.64"
rand = "0.8.5"
reqwest = { version = "0.12.5", features = ["__rustls"] }
time = "0.3.36"
uuid = { version = "1.9.1", features = ["v4"] }

data = { path = "../data", version = "0.1.0" }