name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      scylladb:
        image: scylladb/scylla:latest
        ports:
          - "9042:9042"

    steps:
      - uses: actions/checkout@v4
      - name: Cargo fmt check
        run: cargo fmt --check
      - name: Build
        run: cargo build --verbose --workspace
      - name: Run unit tests
        run: cargo test --verbose --workspace -F test_logging -- --skip integration
      - name: Run integration tests
        run: cargo test --verbose --workspace -F test_logging integration
